# 1. Import numpy as np and see version

In [2]:
import numpy as np
np.__version__

'1.16.4'

# 2. How to create a 1D Array

In [7]:
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. Create a boolean Array

In [9]:
bool_arr = np.full((3,3), True, dtype = bool)
bool_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
bool_arr2 = np.ones((3,3), dtype = bool)
bool_arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4 .Extract all odd numbers from an array

In [ ]:
arr1 = np.arange(10)

#My Solution:
odds = filter(lambda x : x % 2 != 0, arr1)
np.array(list(odds))

# Easier solution is as follows
#arr1[arr1 % 2 != 0]

# 5. Replace all odd numbers in array with -1

In [23]:
#My Solution:
arr1[arr1 % 2 != 0] = -1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6.Replace all odd numbers in arr with -1 without changing arr

In [25]:
arr1 = np.arange(10)
arr2 = np.where (arr1 % 2 != 0, -1, arr1)
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# 7.Convert 1d to 2d array with 2 rows

In [30]:
arr1 = np.arange(10)
arr1 = arr1.reshape(2,5) #or, arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8.Stack 2 arrays vertically

In [37]:
arr1 = np.ones(4)
arr2 = np.zeros(4)
print(np.vstack([arr1,arr2]))

[[1. 1. 1. 1.]
 [0. 0. 0. 0.]]


# 9. Stack 2 arrays horizontally

In [38]:
print(np.hstack([arr1,arr2]))

[1. 1. 1. 1. 0. 0. 0. 0.]


# 10. Create pattern like follows using numpy
    input => np.array([1,2,3])
    output => array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [50]:
#My Solution
arr3 = np.array([1,2,3])
repeat = np.repeat(arr3,3)
#print(np.hstack([repeat,arr3,arr3,arr3]))

#Simpler Solution
print(np.hstack([np.repeat(arr3,3), np.tile(arr3,3)]))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# 11. Common Items between 2 arrays

In [64]:
#My Solution
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#print(set(a).intersection(set(b)))

#Simpler Solution
np.intersect1d(a,b)

array([2, 4])

# 12.From array a remove all items present in array b

In [66]:
#My Solution
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


# 13. Get the positions where elements of a and b match

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

# 14.Get all items between 5 and 10 from a.

In [73]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

# 15.Convert the function maxx that works on two scalars, to work on two arrays.

In [76]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx)
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

# 16. Swap two columns in a 2d numpy array

In [86]:
arr = np.arange(9).reshape(3,3)
arr
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 17. Swap two rows

In [89]:
arr = np.arange(9).reshape(3,3)
arr[[2,1,0],:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 18. Reverse the rows of 2D array

In [90]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19. Reverse the columns of 2D array

In [91]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20.Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [107]:
arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
arr

array([[5.94107651, 8.40924549, 6.3160994 ],
       [5.50114632, 5.13757827, 5.92577729],
       [9.63106764, 7.68028955, 7.39736662],
       [8.90811366, 9.81367799, 6.6497596 ],
       [8.85239743, 7.1846122 , 5.57088504]])

# 21.Print or show only 3 decimal places of the numpy array rand_arr.

In [110]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.126, 0.042, 0.105],
       [0.032, 0.221, 0.663],
       [0.438, 0.446, 0.248],
       [0.389, 0.498, 0.57 ],
       [0.715, 0.36 , 0.643]])