# 1. Import numpy as np and see version

In [4]:
import numpy as np
np.__version__

'1.16.4'

# 2. How to create a 1D Array

In [7]:
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. Create a boolean Array

In [9]:
bool_arr = np.full((3,3), True, dtype = bool)
bool_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
bool_arr2 = np.ones((3,3), dtype = bool)
bool_arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4 .Extract all odd numbers from an array

In [16]:
arr1 = np.arange(10)
odds = arr1.filter(x <= x % 2 != 0)

AttributeError: 'numpy.ndarray' object has no attribute 'filter'